apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: install-sandbox-rhoam-operator
objects:
  - apiVersion: operators.coreos.com/v1alpha1
    kind: CatalogSource
    metadata:
      name: rhmi-operator
      namespace: ${RHOAM_NAMESPACE}
    spec:
      displayName: RHOAM Operators
      image: ${INDEX_IMAGE}
      sourceType: grpc
      updateStrategy:
        registryPoll:
          interval: 5m0s
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: ${OPERATOR_GROUP_NAME}
      namespace: ${RHOAM_NAMESPACE}
    spec:
      targetNamespaces:
        - ${RHOAM_NAMESPACE}
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: ${SUBSCRIPTION_NAME}
      namespace: ${RHOAM_NAMESPACE}
    spec:
      channel: ${CHANNEL}
      installPlanApproval: Automatic
      name: integreatly
      source: ${CATALOG_SOURCE_CONFIG_NAME}
      sourceNamespace: ${CATALOG_SOURCE_CONFIG_NAMESPACE}
parameters:
  - name: RHOAM_NAMESPACE
    value: redhat-rhoam-operator
  - name: INDEX_IMAGE
    value: quay.io/osd-addons/integr8ly-integreatly-operator-index:v4.8-v1.15.0-5
  - name: OPERATOR_GROUP_NAME
    value: redhat-rhoam-operator
  - name: SUBSCRIPTION_NAME
    value: managed-api-service
  - description: The name of the channel
    displayName: Channel Name
    name: CHANNEL
    value: alpha
  - description: The name of the catalog source config
    displayName: Catalog Source Config Name
    name: CATALOG_SOURCE_CONFIG_NAME
    value: rhmi-operator
  - description: The name of the catalog source config namespace
    displayName: Catalog Source Config Namespace
    name: CATALOG_SOURCE_CONFIG_NAMESPACE
    value: redhat-rhoam-operator